### PR TITLE
Hardknott overrides

### PR DESCRIPTION
**Pull request by nsdrude**
The hardknott branch of meta-freescale-ml will not build due to overrides syntax.

This pull request reverts overrides syntax from `:` to `_`

### CODE REVIEW

**Comment by otavio** [comment]
Why? Hardknott uses the new overrides format.

**Comment by nsdrude** [comment]
> Why? Hardknott uses the new overrides format.

This is true, starting in hardknott-3.3.3, which includes the following patches:
https://git.yoctoproject.org/poky/commit/?h=hardknott&id=666d3421389cc3c01c56e92199cc32bddf1922de
https://git.yoctoproject.org/poky/commit/?h=hardknott&id=14c5392fded42f17962e1cc07fcc0446881b4fa0

However, earlier versions of hardknott will fail to parse, for example:

`ERROR: ParseError at ./sources/meta-freescale-ml/recipes-devtools/armnn-swig/armnn-swig.inc:53: unparsed line: 'do_configure:append() {'`

In any case, my main objective is to update the meta-freescale-ml hardknott branch recipes to be aligned to NXP hardknott-5.10.72-2.2.0, and these recipes use the old syntax.

What do you recommend?

**Comment by otavio** [comment]
We support the latest hardknoot, so it must be converted to the new overrides syntax and sent. In any case, it must be sent to the master first and then backported.

**Comment by nsdrude** [comment]
Closing. As discussed, I will resubmit to master with new overrides syntax

**Pull request closed without merging**
