### PR TITLE
python3-pyeiq: add new recipe

### PR DESCRIPTION
**Pull request by zandrey**
Add new recipe, which generates a package containing PyeIQ - Python Demo Framework for eIQ on i.MX Processors.

Cc: @chrisdimich

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by gibsson** [comment]
Hi,
I wouldn't add that package as:
1- It isn't maintained
2- The person who created it is not part of NXP any more
3- Many examples include prebuilt binaries that don't apply with any other release than 2.2.0
Regards,
Gary

**Comment by gibsson** [comment]
Arf, too late

**Comment by otavio** [comment]
It is not, if you guys decide to not include it we just revert it.

**Comment by telelaci** [comment]
I agree with Gary.
It would be a very nice addition but it's an abandoned project.
https://pyeiq.dev/
The latest compatible BSP is 5.4.47_2.2.0 , that's quite old.
It doesn't work with 5.4.70 ... or 5.10.9 ... because it's linked against opencv4.2 and it's not opensource despite of this:
https://source.codeaurora.org/external/imxsupport/pyeiq
,so you can't rebuild it actually.

**Comment by zandrey** [comment]
@gibsson @telelaci 

Thanks a lot for the information here! I was not aware that the Project has been abandoned from NXP, and I'm quite sad to hear it... 😞 

Are you guys sure that this package had no further maintenance plan from the original author, even though he parted ways with NXP?

For me, this commit was rather a payback of a technical debt I've discovered on my end. I've made this recipe awhile ago, and till this repository was created - I had no proper place to contribute it.

But with the information you provided - maybe it indeed makes sense to remove this submission.

-- andrey

**Comment by gibsson** [comment]
You can try contacting him here:
https://github.com/diegohdorta/pyeiq

But clearly NXP doesn't mention PyEIQ in their ML user guide:
https://www.nxp.com/docs/en/user-guide/IMX-MACHINE-LEARNING-UG.pdf

**Comment by zandrey** [comment]
@gibsson Thanks for the info! I would try to contact the author to check on the future plans for this package.

@otavio I guess it make sense to revert this PR and remove the recipe for now, at least until I get some information from the author whether there is an interest to support this component further.

Once again - sorry guys for introducing this recipe, I was just trying to pay my debts not knowing the package is already stale.

-- andrey

**Comment by gibsson** [comment]
Don't be sorry Andrey, that's an honest mistake.
We should have made it clear why we didn't include it in meta-ml in the first place.

**Comment by otavio** [comment]
@zandrey mind to prepare a PR reverting it?

**Comment by zandrey** [comment]
> 
> 
> @zandrey mind to prepare a PR reverting it?

Sure, #10 is submitted.

**Pull request merged**
