### PR TITLE
Upgrade layer for kirkstone compatibility

### PR DESCRIPTION
**Pull request by otavio**
- conf: layer: set compatibility as kirkstone
- tensorflow-lite: rename SSTATE_DUPWHITELIST to SSTATE_ALLOW_OVERLAP_FILES
- Fix SPDX license references

### CODE REVIEW

**Comment by gibsson** [comment]
Is the "rename SSTATE_DUMPWHITELIST to SSTATE_ALLOW_OVERLAP_FILES" fixing the issue Chris was reporting?
If so it'd be great to have the error message it fixes in the commit log for future reference.
Thanks

**Comment by otavio** [comment]
> Is the "rename SSTATE_DUMPWHITELIST to SSTATE_ALLOW_OVERLAP_FILES" fixing the issue Chris was reporting? If so it'd be great to have the error message it fixes in the commit log for future reference. Thanks

I don't think so; this is a kirkstone rework made in OE-Core. I am still doing fixes here until I reproduce his error.

**Comment by gibsson** [comment]
Ok, no problem, then it all looks good ;)

**Comment by chrisdimich** [comment]
I agree with Gary, looks good to me!

**Pull request merged**
